version: "3.7"
services:
  nlp-dev:
    build:
      context: .
      dockerfile: dockerfile.dev
    image: nlp-dev:latest
    container_name: nlp-dev
    volumes:
      - ./work:/work
    ports:
      - '8080:8080'
    tty: true

  nlp-notebook:
    build:
      context: .
      dockerfile: dockerfile.jup
    image: jupyter/datascience-notebook
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_ENABLE_LAB=yes
    volumes:
      - ./jupyter:/jupyter
    command: start-notebook.sh --NotebookApp.token=''
